### ISSUE TITLE
TypeError: InstagramApi.get is not a function

### ISSUE THREAD

**Issue by 89z** [Scrip7/simple-instagram-api#1]
Using the example from here [1]:

~~~js
import InstagramApi from "simple-instagram-api";
const code = "CMf29lRF52W";

InstagramApi.get(code).then((result) => {
  console.log(result);
});
~~~

I get this result:

~~~
InstagramApi.get(code).then((result) => {
             ^

TypeError: InstagramApi.get is not a function
    at file:///D:/Desktop/ig.mjs:6:14
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
    at async handleMainPromise (node:internal/modules/run_main:63:12)
~~~

Here is my `package.json`:

~~~json
{
  "dependencies": {
    "simple-instagram-api": "^2.2.0"
  }
}
~~~

1. https://github.com/Scrip7/simple-instagram-api#-example-usage

**Comment by Scrip7** [comment]
The given example is in TypeScript
Do you use TypeScript or vanilla JS?
May you try this and LMK if it works? @89z 

```typescript
import * as InstagramApi from "simple-instagram-api";
```

**Comment by 89z** [comment]
> 
> 
> The given example is in TypeScript
> Do you use TypeScript or vanilla JS?

I dont understand. I am using Node, what is the problem?

**Comment by Scrip7** [comment]
> > The given example is in TypeScript
> > Do you use TypeScript or vanilla JS?
> 
> I dont understand. I am using Node, what is the problem?

Try the code I gave, if it didn't work try this and let me know the results

```javascript
const InstagramApi = require("simple-instagram-api");
```

**Comment by 89z** [comment]
I dont understand. Here [1], you have this:

~~~
npm install simple-instagram-api
~~~

Which is Node. If you arent using Node, what are you using? And if you arent using Node, then why are you using the Node package manager. Also, if you arent using Node, you should mention that in the Readme, as well as what tool needs to be used to run the examples.

1. https://github.com/Scrip7/simple-instagram-api#-installation

**Comment by Scrip7** [comment]
I am using Node.JS buddy,
Please try the given example codes I gave regarding the different ways to import the package.
And let me know the results 😄

**Comment by 89z** [comment]
I am using Node v16.8.0. I dont understand why I can just use the code without changing it?

**Comment by Scrip7** [comment]
> I am using Node v16.8.0. I dont understand why I cant just use the code without changing it?

This is the third time I'm asking,
Would you please change your import line to one of these and LMK the results?

```typescript
import * as InstagramApi from "simple-instagram-api";
```

```javascript
const InstagramApi = require("simple-instagram-api");
```

**Comment by 89z** [comment]
> This is the third time I'm asking,

I dont get why you refuse to answer my question. I am using Node, so why do I need to change the code?

> Would you please change your import line to one of these and LMK the results?

Using the the below code, I get the exact same error:

~~~js
const InstagramApi = require("simple-instagram-api");
const code = "CMf29lRF52W";

InstagramApi.get(code).then((result) => {
  console.log(result);
});
~~~

**Comment by Scrip7** [comment]
> I dont get why you refuse to answer my question. I am using Node, so why do I need to change the code?

The example I wrote is in TypeScript
That is not my issue if you don't know how to import a package in your project in Node.JS

Try to figure out why can't you import the package properly, then you should be fine.

**Comment by 89z** [comment]
Nope, its your package. I just ran this code with no problem:

~~~js
import { lazy } from 'lazy-arr';
let numbers = lazy(x => x * 2);
console.log(numbers[5]);
~~~

https://github.com/bcherny/lazy-arr

**Comment by 89z** [comment]
I see you change your code:

https://github.com/Scrip7/simple-instagram-api/commit/6e78e733

because you realize that this is not valid:

~~~js
import InstagramApi from "simple-instagram-api";
~~~

and you want to blame me? Shame on you.

**Comment by 89z** [comment]
@Scrip7 you watch yours:

> That is not my issue if you don't know how to import a package in your project in Node.JS

I know how to import to Node. Do you know how to admit when you were wrong. Because you were, painfully, obviously wrong. This code is not valid:

~~~js
import InstagramApi from "simple-instagram-api";
~~~

which you now know, because you patched it **10 minutes ago**. But yet you want to blame me, when the obvious problem was your invalid code. Its a sad person who cant admit when they are wrong. Grow up dude.

**Comment by Scrip7** [comment]
Yeap, you have no idea what you talking about
I had in mind to rewrite the package's API again and I barely did it and didn't even release it yet lol
Plus the thing I merged is not even published in NPM
https://www.npmjs.com/package/simple-instagram-api
Again you clearly don't have any idea and cluelessly blaming me for no reason, move on buddy
This conversation is over

**Comment by 89z** [comment]
> Yeap, you have no idea what you talking about

Poor guy, just because you say something doesnt make it true. However I can say you have no idea what youre talking about, and actually back it up. For example, you wrote this code:

~~~js
import InstagramApi from "simple-instagram-api";
~~~

which can be seen here:

https://github.com/Scrip7/simple-instagram-api/blob/440f418dd083c7100ead3e80acf84d171f886dc4/README.md

Of course you now realize that this isnt valid code, so you patched it:

https://github.com/Scrip7/simple-instagram-api/commit/6e78e733c8c6728789fb871c2e654cc7563b8a96

but you are too afraid to admit you made a mistake. It OK man, no one is perfect, we all make mistakes. Hopefully one day you will mature and grow. Good luck.
